# SPDX-FileCopyrightText: 2024 Telef贸nica Innovaci贸n Digital and contributors
# SPDX-License-Identifier: Apache-2.0

name: 'Markdown Confluence Sync'
description: 'GitHub Action to sync markdown files to Confluence'
author: 'Telef贸nica Innovaci贸n Digital'

# Define your inputs here.
inputs:
  log-level:
    description: 'Log level'
    type: choice
    options:
      - 'silly'
      - 'debug'
      - 'verbose'
      - 'info'
      - 'warn'
      - 'error'
      - 'silent'
  mode:
    description: 'Mode to sync the markdown files'
    type: choice
    options:
      - 'flat'
      - 'tree'
  files-pattern:
    description: 'Pattern to filter the files to sync in flat mode'
    type: string
  docs-dir:
    description: 'Directory where the markdown files are located'
    type: string
  confluence-url:
    description: 'Confluence URL'
    type: string
  confluence-personal-access-token:
    description: 'Confluence personal access token'
    type: string
  confluence-space-key:
    description: 'Key of the Confluence space where the pages will be synced'
    type: string
  confluence-root-page-id:
    description: 'ID of the Confluence page where the pages will be synced'
    type: string
  confluence-root-page-name:
    description: 'Customize Confluence page titles by adding a prefix to all of them for improved organization and clarity'
    type: string
  confluence-notice-message:
    description: 'Notice message to add at the beginning of the Confluence pages'
    type: string
  confluence-notice-template:
    description: 'Template string to use for the notice message'
    type: string
  confluence-dry-run:
    description:
      'Log create, update or delete requests to Confluence instead of really
      making them'
    type: boolean

runs:
  using: node22
  main: dist/index.js
