# SPDX-FileCopyrightText: 2024 Telefónica Innovación Digital
# SPDX-License-Identifier: MIT

name: Test E2E

on:
  push:
    branches:
      - main
      - fix/crc-184/mermaid

permissions:
  contents: read

jobs:
  sync-to-confluence:
    environment: production
    name: Sync Docs to Confluence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Sync Docs
        id: sync-docs
        uses: ./
        with:
          mode: id
          docs-dir: '.'
          files-pattern: '*.md'
          files-metadata: |
            [
              {
                "path": "README.md",
                "id": "${{ vars.CONFLUENCE_README_PAGE_ID }}",
                "title": "[Cross] [Markdown Confluence Sync] Github action"
              },
              {
                "path": "CHANGELOG.md",
                "id": "${{ vars.CONFLUENCE_CHANGELOG_PAGE_ID }}",
                "title": "[Cross] [Markdown Confluence Sync] [Github action] Releases"
              }
            ]
          confluence-url: ${{ vars.CONFLUENCE_URL }}
          confluence-space-key: ${{ vars.CONFLUENCE_SPACE_KEY }}
          confluence-personal-access-token: ${{ secrets.CONFLUENCE_PAT }}
          log-level: debug

  test-e2e:
    environment: production
    name: Test E2E
    runs-on: ubuntu-latest
    needs: sync-to-confluence

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node
        id: setup-node
        with:
          npm-token: ${{ secrets.NPM_TOKEN_XCUT }}
        
      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          CONFLUENCE_URL: ${{ vars.CONFLUENCE_URL }}
          CONFLUENCE_PAT: ${{ secrets.CONFLUENCE_PAT }}
          CONFLUENCE_README_PAGE_ID: ${{ vars.CONFLUENCE_README_PAGE_ID }}
          CONFLUENCE_CHANGELOG_PAGE_ID: ${{ vars.CONFLUENCE_CHANGELOG_PAGE_ID }}
